
wire kernel_monitor_reset;
wire kernel_monitor_clock;
wire kernel_monitor_report;
assign kernel_monitor_reset = ~ap_rst_n;
assign kernel_monitor_clock = ap_clk;
assign kernel_monitor_report = 1'b0;
wire [1:0] axis_block_sigs;
wire [14:0] inst_idle_sigs;
wire [11:0] inst_block_sigs;
wire kernel_block;

assign axis_block_sigs[0] = ~conv_1d_cl_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_8u_config2_U0.input_layer_TDATA_blk_n;
assign axis_block_sigs[1] = ~dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_3u_config15_U0.layer15_out_TDATA_blk_n;

assign inst_idle_sigs[0] = conv_1d_cl_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_8u_config2_U0.ap_idle;
assign inst_block_sigs[0] = (conv_1d_cl_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_8u_config2_U0.ap_done & ~conv_1d_cl_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_8u_config2_U0.ap_continue) | ~conv_1d_cl_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_8u_config2_U0.grp_compute_output_buffer_1d_array_array_ap_fixed_16_6_5_3_0_8u_config2_s_fu_126.layer2_out_blk_n;
assign inst_idle_sigs[1] = normalize_array_ap_fixed_8u_array_ap_fixed_10_5_5_3_0_8u_config3_U0.ap_idle;
assign inst_block_sigs[1] = (normalize_array_ap_fixed_8u_array_ap_fixed_10_5_5_3_0_8u_config3_U0.ap_done & ~normalize_array_ap_fixed_8u_array_ap_fixed_10_5_5_3_0_8u_config3_U0.ap_continue) | ~normalize_array_ap_fixed_8u_array_ap_fixed_10_5_5_3_0_8u_config3_U0.layer2_out_blk_n | ~normalize_array_ap_fixed_8u_array_ap_fixed_10_5_5_3_0_8u_config3_U0.layer3_out_blk_n;
assign inst_idle_sigs[2] = thresholded_relu_array_ap_fixed_array_ap_fixed_8u_thresholdedrelu_config4_U0.ap_idle;
assign inst_block_sigs[2] = (thresholded_relu_array_ap_fixed_array_ap_fixed_8u_thresholdedrelu_config4_U0.ap_done & ~thresholded_relu_array_ap_fixed_array_ap_fixed_8u_thresholdedrelu_config4_U0.ap_continue) | ~thresholded_relu_array_ap_fixed_array_ap_fixed_8u_thresholdedrelu_config4_U0.layer3_out_blk_n | ~thresholded_relu_array_ap_fixed_array_ap_fixed_8u_thresholdedrelu_config4_U0.layer4_out_blk_n;
assign inst_idle_sigs[3] = pooling1d_cl_array_ap_fixed_8u_array_ap_fixed_8_4_5_3_0_8u_config5_U0.ap_idle;
assign inst_block_sigs[3] = (pooling1d_cl_array_ap_fixed_8u_array_ap_fixed_8_4_5_3_0_8u_config5_U0.ap_done & ~pooling1d_cl_array_ap_fixed_8u_array_ap_fixed_8_4_5_3_0_8u_config5_U0.ap_continue) | ~pooling1d_cl_array_ap_fixed_8u_array_ap_fixed_8_4_5_3_0_8u_config5_U0.layer4_out_blk_n | ~pooling1d_cl_array_ap_fixed_8u_array_ap_fixed_8_4_5_3_0_8u_config5_U0.layer5_out_blk_n;
assign inst_idle_sigs[4] = conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config6_U0.ap_idle;
assign inst_block_sigs[4] = (conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config6_U0.ap_done & ~conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config6_U0.ap_continue) | ~conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config6_U0.layer5_out_blk_n | ~conv_1d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config6_U0.grp_compute_output_buffer_1d_array_array_ap_fixed_16_6_5_3_0_8u_config6_s_fu_128.layer6_out_blk_n;
assign inst_idle_sigs[5] = normalize_array_ap_fixed_8u_array_ap_fixed_10_5_5_3_0_8u_config7_U0.ap_idle;
assign inst_block_sigs[5] = (normalize_array_ap_fixed_8u_array_ap_fixed_10_5_5_3_0_8u_config7_U0.ap_done & ~normalize_array_ap_fixed_8u_array_ap_fixed_10_5_5_3_0_8u_config7_U0.ap_continue) | ~normalize_array_ap_fixed_8u_array_ap_fixed_10_5_5_3_0_8u_config7_U0.layer6_out_blk_n | ~normalize_array_ap_fixed_8u_array_ap_fixed_10_5_5_3_0_8u_config7_U0.layer7_out_blk_n;
assign inst_idle_sigs[6] = thresholded_relu_array_ap_fixed_array_ap_fixed_8u_thresholdedrelu_config8_U0.ap_idle;
assign inst_block_sigs[6] = (thresholded_relu_array_ap_fixed_array_ap_fixed_8u_thresholdedrelu_config8_U0.ap_done & ~thresholded_relu_array_ap_fixed_array_ap_fixed_8u_thresholdedrelu_config8_U0.ap_continue) | ~thresholded_relu_array_ap_fixed_array_ap_fixed_8u_thresholdedrelu_config8_U0.layer7_out_blk_n | ~thresholded_relu_array_ap_fixed_array_ap_fixed_8u_thresholdedrelu_config8_U0.layer8_out_blk_n;
assign inst_idle_sigs[7] = pooling1d_cl_array_ap_fixed_8u_array_ap_fixed_8_4_5_3_0_8u_config9_U0.ap_idle;
assign inst_block_sigs[7] = (pooling1d_cl_array_ap_fixed_8u_array_ap_fixed_8_4_5_3_0_8u_config9_U0.ap_done & ~pooling1d_cl_array_ap_fixed_8u_array_ap_fixed_8_4_5_3_0_8u_config9_U0.ap_continue) | ~pooling1d_cl_array_ap_fixed_8u_array_ap_fixed_8_4_5_3_0_8u_config9_U0.layer8_out_blk_n | ~pooling1d_cl_array_ap_fixed_8u_array_ap_fixed_8_4_5_3_0_8u_config9_U0.layer9_out_blk_n;
assign inst_idle_sigs[8] = dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_32u_config12_U0.ap_idle;
assign inst_block_sigs[8] = (dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_32u_config12_U0.ap_done & ~dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_32u_config12_U0.ap_continue) | ~dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_32u_config12_U0.grp_dense_array_array_ap_fixed_16_6_5_3_0_32u_config12_Pipeline_DataPrepare_fu_419.layer9_out_blk_n | ~dense_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_32u_config12_U0.layer12_out_blk_n;
assign inst_idle_sigs[9] = normalize_array_ap_fixed_32u_array_ap_fixed_10_5_5_3_0_32u_config13_U0.ap_idle;
assign inst_block_sigs[9] = (normalize_array_ap_fixed_32u_array_ap_fixed_10_5_5_3_0_32u_config13_U0.ap_done & ~normalize_array_ap_fixed_32u_array_ap_fixed_10_5_5_3_0_32u_config13_U0.ap_continue) | ~normalize_array_ap_fixed_32u_array_ap_fixed_10_5_5_3_0_32u_config13_U0.layer12_out_blk_n | ~normalize_array_ap_fixed_32u_array_ap_fixed_10_5_5_3_0_32u_config13_U0.layer13_out_blk_n;
assign inst_idle_sigs[10] = thresholded_relu_array_ap_fixed_array_thresholdedrelu_config14_U0.ap_idle;
assign inst_block_sigs[10] = (thresholded_relu_array_ap_fixed_array_thresholdedrelu_config14_U0.ap_done & ~thresholded_relu_array_ap_fixed_array_thresholdedrelu_config14_U0.ap_continue) | ~thresholded_relu_array_ap_fixed_array_thresholdedrelu_config14_U0.layer13_out_blk_n | ~thresholded_relu_array_ap_fixed_array_thresholdedrelu_config14_U0.layer14_out_blk_n;
assign inst_idle_sigs[11] = dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_3u_config15_U0.ap_idle;
assign inst_block_sigs[11] = (dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_3u_config15_U0.ap_done & ~dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_3u_config15_U0.ap_continue) | ~dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_3u_config15_U0.layer14_out_blk_n;

assign inst_idle_sigs[12] = 1'b0;
assign inst_idle_sigs[13] = conv_1d_cl_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_8u_config2_U0.ap_idle;
assign inst_idle_sigs[14] = dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_3u_config15_U0.ap_idle;

myproject_hls_deadlock_idx0_monitor myproject_hls_deadlock_idx0_monitor_U (
    .clock(kernel_monitor_clock),
    .reset(kernel_monitor_reset),
    .axis_block_sigs(axis_block_sigs),
    .inst_idle_sigs(inst_idle_sigs),
    .inst_block_sigs(inst_block_sigs),
    .block(kernel_block)
);


always @ (kernel_block or kernel_monitor_reset) begin
    if (kernel_block == 1'b1 && kernel_monitor_reset == 1'b0) begin
        find_kernel_block = 1'b1;
    end
    else begin
        find_kernel_block = 1'b0;
    end
end
