-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_40 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_41 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_42 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_43 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_44 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_45 : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_o_ap_vld : OUT STD_LOGIC;
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of myproject_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln161_fu_144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal tmp_fu_172_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln161_fu_156_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_208_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_244_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_280_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_316_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_352_p11 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_iw_fu_96 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal indvars_iv_next_fu_150_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_iw_6 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_172_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_208_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_244_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_280_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_316_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_352_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_172_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_172_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_172_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_172_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_208_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_208_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_208_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_208_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_244_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_244_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_244_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_244_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_280_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_280_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_280_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_280_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_316_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_316_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_316_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_316_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_352_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_352_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_352_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_352_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myproject_sparsemux_9_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component myproject_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_16_1_1_U1 : component myproject_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_i,
        din1 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_i,
        din2 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_i,
        din3 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_40,
        def => tmp_fu_172_p9,
        sel => trunc_ln161_fu_156_p1,
        dout => tmp_fu_172_p11);

    sparsemux_9_2_16_1_1_U2 : component myproject_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_i,
        din1 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_i,
        din2 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_i,
        din3 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_41,
        def => tmp_s_fu_208_p9,
        sel => trunc_ln161_fu_156_p1,
        dout => tmp_s_fu_208_p11);

    sparsemux_9_2_16_1_1_U3 : component myproject_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i,
        din1 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_i,
        din2 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_i,
        din3 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_42,
        def => tmp_1_fu_244_p9,
        sel => trunc_ln161_fu_156_p1,
        dout => tmp_1_fu_244_p11);

    sparsemux_9_2_16_1_1_U4 : component myproject_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_i,
        din1 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_i,
        din2 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_i,
        din3 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_43,
        def => tmp_2_fu_280_p9,
        sel => trunc_ln161_fu_156_p1,
        dout => tmp_2_fu_280_p11);

    sparsemux_9_2_16_1_1_U5 : component myproject_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_i,
        din1 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_i,
        din2 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_i,
        din3 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_44,
        def => tmp_3_fu_316_p9,
        sel => trunc_ln161_fu_156_p1,
        dout => tmp_3_fu_316_p11);

    sparsemux_9_2_16_1_1_U6 : component myproject_sparsemux_9_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "10",
        din2_WIDTH => 16,
        CASE3 => "11",
        din3_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_i,
        din1 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_i,
        din2 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_i,
        din3 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_45,
        def => tmp_4_fu_352_p9,
        sel => trunc_ln161_fu_156_p1,
        dout => tmp_4_fu_352_p11);

    flow_control_loop_pipe_sequential_init_U : component myproject_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_iw_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln161_fu_144_p2 = ap_const_lv1_0)) then 
                    i_iw_fu_96 <= indvars_iv_next_fu_150_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_iw_fu_96 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_iw_6_assign_proc : process(ap_CS_fsm_state1, i_iw_fu_96, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_iw_6 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_iw_6 <= i_iw_fu_96;
        end if; 
    end process;

    icmp_ln161_fu_144_p2 <= "1" when (ap_sig_allocacmp_i_iw_6 = ap_const_lv3_4) else "0";
    indvars_iv_next_fu_150_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_iw_6) + unsigned(ap_const_lv3_1));

    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_i, trunc_ln161_fu_156_p1, tmp_s_fu_208_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_o <= tmp_s_fu_208_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_10_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_i, tmp_fu_172_p11, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_o <= tmp_fu_172_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_11_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_i, trunc_ln161_fu_156_p1, tmp_4_fu_352_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_o <= tmp_4_fu_352_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_12_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_i, trunc_ln161_fu_156_p1, tmp_3_fu_316_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_o <= tmp_3_fu_316_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_13_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_i, trunc_ln161_fu_156_p1, tmp_2_fu_280_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_o <= tmp_2_fu_280_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_i, trunc_ln161_fu_156_p1, tmp_1_fu_244_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_o <= tmp_1_fu_244_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_i, trunc_ln161_fu_156_p1, tmp_s_fu_208_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_o <= tmp_s_fu_208_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_i, tmp_fu_172_p11, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_o <= tmp_fu_172_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_2))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_i, trunc_ln161_fu_156_p1, tmp_4_fu_352_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_o <= tmp_4_fu_352_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_i, trunc_ln161_fu_156_p1, tmp_3_fu_316_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_o <= tmp_3_fu_316_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_i, trunc_ln161_fu_156_p1, tmp_4_fu_352_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_o <= tmp_4_fu_352_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_6_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_i, trunc_ln161_fu_156_p1, tmp_3_fu_316_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_o <= tmp_3_fu_316_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_7_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_i, trunc_ln161_fu_156_p1, tmp_2_fu_280_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_o <= tmp_2_fu_280_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_8_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_i, trunc_ln161_fu_156_p1, tmp_1_fu_244_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_o <= tmp_1_fu_244_p11;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_o <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_i;
        end if; 
    end process;


    p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_3))) then 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_9_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_244_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_2_fu_280_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_3_fu_316_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_4_fu_352_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_fu_172_p9 <= "XXXXXXXXXXXXXXXX";
    tmp_s_fu_208_p9 <= "XXXXXXXXXXXXXXXX";
    trunc_ln161_fu_156_p1 <= ap_sig_allocacmp_i_iw_6(2 - 1 downto 0);

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_i, trunc_ln161_fu_156_p1, tmp_2_fu_280_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o <= tmp_2_fu_280_p11;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_i;
        end if; 
    end process;


    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i, trunc_ln161_fu_156_p1, tmp_1_fu_244_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o <= tmp_1_fu_244_p11;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i;
        end if; 
    end process;


    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_i, trunc_ln161_fu_156_p1, tmp_s_fu_208_p11)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o <= tmp_s_fu_208_p11;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_i;
        end if; 
    end process;


    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_assign_proc : process(ap_CS_fsm_state1, icmp_ln161_fu_144_p2, void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_i, tmp_fu_172_p11, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o <= tmp_fu_172_p11;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o <= void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_i;
        end if; 
    end process;


    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_1))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 <= tmp_4_fu_352_p11;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_0))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15 <= tmp_3_fu_316_p11;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_0))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16 <= tmp_2_fu_280_p11;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_0))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17 <= tmp_1_fu_244_p11;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_0))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18 <= tmp_s_fu_208_p11;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_0))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19 <= tmp_fu_172_p11;

    void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln161_fu_144_p2, trunc_ln161_fu_156_p1)
    begin
        if (((icmp_ln161_fu_144_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln161_fu_156_p1 = ap_const_lv2_0))) then 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld <= ap_const_logic_1;
        else 
            void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
