-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_compute_output_buffer_1d_array_array_ap_fixed_16_6_5_3_0_8u_config2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    layer2_out_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    layer2_out_full_n : IN STD_LOGIC;
    layer2_out_write : OUT STD_LOGIC;
    layer2_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    layer2_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of myproject_compute_output_buffer_1d_array_array_ap_fixed_16_6_5_3_0_8u_config2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal sX_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pX_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal layer2_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal and_ln350_reg_521 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_144_reg_480 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_145_reg_485 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_146_reg_490 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_147_reg_495 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_148_reg_500 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_149_reg_505 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln350_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln350_reg_513 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal and_ln350_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_out_reg_525 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal res_out_14_reg_530 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_out_15_reg_535 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_out_16_reg_540 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_out_4_reg_545 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_out_5_reg_550 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_out_6_reg_555 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_out_7_reg_560 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_start : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_done : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_idle : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_ready : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_o_ap_vld : STD_LOGIC;
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_o_ap_vld : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_start : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_done : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_idle : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_ready : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln376_fu_462_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_storemerge_phi_fu_160_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state5 : BOOLEAN;
    signal icmp_ln369_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_start_reg : STD_LOGIC := '0';
    signal add_ln369_fu_438_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_371_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal icmp_ln350_2_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln376_fu_455_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_82 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_83 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_84 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_85 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_86 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_87 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_o_ap_vld : OUT STD_LOGIC );
    end component;


    component myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167 : component myproject_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_start,
        ap_done => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_done,
        ap_idle => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_idle,
        ap_ready => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_ready,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_82 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_144_reg_480,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_83 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_145_reg_485,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_84 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_146_reg_490,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_85 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_147_reg_495,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_86 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_148_reg_500,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_87 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_149_reg_505,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19 => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18 => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17 => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16 => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15 => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_i => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_i => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_i => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_i => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_o => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_o_ap_vld => grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_o_ap_vld);

    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225 : component myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_start,
        ap_done => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_done,
        ap_idle => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_idle,
        ap_ready => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_ready,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10 => void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14 => p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14,
        ap_return_0 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_0,
        ap_return_1 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_1,
        ap_return_2 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_2,
        ap_return_3 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_3,
        ap_return_4 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_4,
        ap_return_5 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_5,
        ap_return_6 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_6,
        ap_return_7 => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_7);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_ready = ap_const_logic_1)) then 
                    grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = and_ln350_fu_387_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_ready = ap_const_logic_1)) then 
                    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    pX_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                if ((icmp_ln369_fu_443_p2 = ap_const_lv1_1)) then 
                    pX_3 <= ap_const_lv32_0;
                elsif ((icmp_ln369_fu_443_p2 = ap_const_lv1_0)) then 
                    pX_3 <= add_ln369_fu_438_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                and_ln350_reg_521 <= and_ln350_fu_387_p2;
                icmp_ln350_reg_513 <= icmp_ln350_fu_361_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14 <= p_read5;
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15 <= p_read4;
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16 <= p_read3;
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17 <= p_read2;
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18 <= p_read1;
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19 <= p_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_144_reg_480 <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_19;
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_145_reg_485 <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_18;
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_146_reg_490 <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_17;
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_147_reg_495 <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_16;
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_148_reg_500 <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_15;
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_149_reg_505 <= p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_14;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_20_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_21_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_22_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_23_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_24_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_25_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_26_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_27_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_28_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_29_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_30_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_31_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_32_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9_33_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                res_out_14_reg_530 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_1;
                res_out_15_reg_535 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_2;
                res_out_16_reg_540 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_3;
                res_out_4_reg_545 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_4;
                res_out_5_reg_550 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_5;
                res_out_6_reg_555 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_6;
                res_out_7_reg_560 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_7;
                res_out_reg_525 <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_return_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                sX_3 <= ap_phi_mux_storemerge_phi_fu_160_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19 <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state5, ap_CS_fsm_state3, and_ln350_fu_387_p2, ap_CS_fsm_state4, grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_done, grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_done, ap_block_state5, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_lv1_0 = and_ln350_fu_387_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln369_fu_438_p2 <= std_logic_vector(unsigned(pX_3) + unsigned(ap_const_lv32_1));
    add_ln376_fu_462_p2 <= std_logic_vector(unsigned(sX_3) + unsigned(select_ln376_fu_455_p3));
    and_ln350_fu_387_p2 <= (icmp_ln350_fu_361_p2 and icmp_ln350_2_fu_381_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_done)
    begin
        if ((grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_done)
    begin
        if ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5)
    begin
        if ((ap_const_boolean_1 = ap_block_state5)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state5_assign_proc : process(layer2_out_full_n, and_ln350_reg_521)
    begin
                ap_block_state5 <= ((ap_const_lv1_1 = and_ln350_reg_521) and (layer2_out_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5, ap_block_state5)
    begin
        if ((((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_160_p4_assign_proc : process(ap_CS_fsm_state5, add_ln376_fu_462_p2, icmp_ln369_fu_443_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
            if ((icmp_ln369_fu_443_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_storemerge_phi_fu_160_p4 <= ap_const_lv32_0;
            elsif ((icmp_ln369_fu_443_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_storemerge_phi_fu_160_p4 <= add_ln376_fu_462_p2;
            else 
                ap_phi_mux_storemerge_phi_fu_160_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_storemerge_phi_fu_160_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, ap_block_state5)
    begin
        if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_start <= grp_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth_fu_167_ap_start_reg;
    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_start <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_16_6_5_3_0_config2_mult_s_fu_225_ap_start_reg;
    icmp_ln350_2_fu_381_p2 <= "1" when (signed(tmp_fu_371_p4) > signed(ap_const_lv30_0)) else "0";
    icmp_ln350_fu_361_p2 <= "1" when (sX_3 = ap_const_lv32_4) else "0";
    icmp_ln369_fu_443_p2 <= "1" when (add_ln369_fu_438_p2 = ap_const_lv32_D0) else "0";

    layer2_out_blk_n_assign_proc : process(layer2_out_full_n, ap_CS_fsm_state5, and_ln350_reg_521)
    begin
        if (((ap_const_lv1_1 = and_ln350_reg_521) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            layer2_out_blk_n <= layer2_out_full_n;
        else 
            layer2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer2_out_din <= (((((((res_out_7_reg_560 & res_out_6_reg_555) & res_out_5_reg_550) & res_out_4_reg_545) & res_out_16_reg_540) & res_out_15_reg_535) & res_out_14_reg_530) & res_out_reg_525);

    layer2_out_write_assign_proc : process(ap_CS_fsm_state5, and_ln350_reg_521, ap_block_state5)
    begin
        if (((ap_const_lv1_1 = and_ln350_reg_521) and (ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            layer2_out_write <= ap_const_logic_1;
        else 
            layer2_out_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln376_fu_455_p3 <= 
        ap_const_lv32_FFFFFFFF when (icmp_ln350_reg_513(0) = '1') else 
        ap_const_lv32_1;
    tmp_fu_371_p4 <= pX_3(31 downto 2);
end behav;
