-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_16_6_5_3_0_config15_s_w15_ROMfYi is 
    generic(
             DataWidth     : integer := 10; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 96
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of myproject_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_16_6_5_3_0_config15_s_w15_ROMfYi is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000101010", 1 => "1100100100", 2 => "0101100010", 3 => "1001110111", 
    4 => "0010001000", 5 => "0011000101", 6 => "1010001011", 7 => "0000001000", 
    8 => "1001100000", 9 => "0000010010", 10 => "1110000001", 11 => "1101011010", 
    12 => "0100010100", 13 => "1100101001", 14 => "0110010000", 15 => "1011000110", 
    16 => "0100100001", 17 => "0110010101", 18 => "0011110001", 19 => "0001000110", 
    20 => "0001110011", 21 => "0101000010", 22 => "0100011001", 23 => "0010000101", 
    24 => "0011011011", 25 => "0100001100", 26 => "0101101111", 27 => "0100000011", 
    28 => "0000011101", 29 => "0010001110", 30 => "0011111001", 31 => "1100001100", 
    32 => "1011001010", 33 => "0101011001", 34 => "1010001001", 35 => "1011001100", 
    36 => "0111100011", 37 => "1100000001", 38 => "0001111110", 39 => "1111010101", 
    40 => "1011101100", 41 => "0111010010", 42 => "1010001101", 43 => "1001110111", 
    44 => "0001000001", 45 => "0110011111", 46 => "0001001000", 47 => "0011111111", 
    48 => "1101001110", 49 => "0010001000", 50 => "1110100010", 51 => "0100010111", 
    52 => "1010011000", 53 => "1101100100", 54 => "1110011111", 55 => "0110010111", 
    56 => "0110101100", 57 => "0101010011", 58 => "1110101111", 59 => "0101101101", 
    60 => "0000100011", 61 => "1010011000", 62 => "0010000001", 63 => "0001010111", 
    64 => "0100110101", 65 => "0100100111", 66 => "1111100010", 67 => "0011000010", 
    68 => "1100101110", 69 => "1101011011", 70 => "1101011111", 71 => "1010111100", 
    72 => "0111101000", 73 => "1101010111", 74 => "1011101011", 75 => "1010000011", 
    76 => "0100011000", 77 => "0001000001", 78 => "0001000110", 79 => "0101101110", 
    80 => "0010111001", 81 => "1100111100", 82 => "1101101100", 83 => "0001010100", 
    84 => "1110100111", 85 => "1011011101", 86 => "0101000100", 87 => "1011000101", 
    88 => "1111001100", 89 => "1100110111", 90 => "0101010010", 91 => "0010111001", 
    92 => "0110010001", 93 => "0001101000", 94 => "0011111101", 95 => "0110011101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

