-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_thresholded_relu_array_ap_fixed_array_thresholdedrelu_config14_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer13_out_dout : IN STD_LOGIC_VECTOR (319 downto 0);
    layer13_out_empty_n : IN STD_LOGIC;
    layer13_out_read : OUT STD_LOGIC;
    layer13_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer13_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer14_out_din : OUT STD_LOGIC_VECTOR (255 downto 0);
    layer14_out_full_n : IN STD_LOGIC;
    layer14_out_write : OUT STD_LOGIC;
    layer14_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer14_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of myproject_thresholded_relu_array_ap_fixed_array_thresholdedrelu_config14_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_45 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000101";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    constant ap_const_lv32_6D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101101";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_81 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000001";
    constant ap_const_lv32_82 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000010";
    constant ap_const_lv32_8B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001011";
    constant ap_const_lv32_8C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001100";
    constant ap_const_lv32_95 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010101";
    constant ap_const_lv32_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010110";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_A9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101001";
    constant ap_const_lv32_AA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101010";
    constant ap_const_lv32_B3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110011";
    constant ap_const_lv32_B4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110100";
    constant ap_const_lv32_BD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111101";
    constant ap_const_lv32_BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111110";
    constant ap_const_lv32_C7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000111";
    constant ap_const_lv32_C8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001000";
    constant ap_const_lv32_D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010001";
    constant ap_const_lv32_D2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010010";
    constant ap_const_lv32_DB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011011";
    constant ap_const_lv32_DC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011100";
    constant ap_const_lv32_E5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100101";
    constant ap_const_lv32_E6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100110";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111001";
    constant ap_const_lv32_FA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111010";
    constant ap_const_lv32_103 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000011";
    constant ap_const_lv32_104 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000100";
    constant ap_const_lv32_10D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001101";
    constant ap_const_lv32_10E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001110";
    constant ap_const_lv32_117 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010111";
    constant ap_const_lv32_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011000";
    constant ap_const_lv32_121 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100001";
    constant ap_const_lv32_122 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100010";
    constant ap_const_lv32_12B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101011";
    constant ap_const_lv32_12C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101100";
    constant ap_const_lv32_135 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110101";
    constant ap_const_lv32_136 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110110";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_3D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111101";
    constant ap_const_lv32_44 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000100";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_51 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010001";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011011";
    constant ap_const_lv32_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100010";
    constant ap_const_lv32_65 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100101";
    constant ap_const_lv32_6C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101100";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110110";
    constant ap_const_lv32_79 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111001";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_83 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000011";
    constant ap_const_lv32_8A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001010";
    constant ap_const_lv32_8D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001101";
    constant ap_const_lv32_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010100";
    constant ap_const_lv32_97 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010111";
    constant ap_const_lv32_9E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011110";
    constant ap_const_lv32_A1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100001";
    constant ap_const_lv32_A8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101000";
    constant ap_const_lv32_AB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101011";
    constant ap_const_lv32_B2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110010";
    constant ap_const_lv32_B5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110101";
    constant ap_const_lv32_BC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111100";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000110";
    constant ap_const_lv32_C9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001001";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_D3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010011";
    constant ap_const_lv32_DA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011010";
    constant ap_const_lv32_DD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011101";
    constant ap_const_lv32_E4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100100";
    constant ap_const_lv32_E7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100111";
    constant ap_const_lv32_EE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101110";
    constant ap_const_lv32_F1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110001";
    constant ap_const_lv32_F8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111000";
    constant ap_const_lv32_FB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111011";
    constant ap_const_lv32_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000010";
    constant ap_const_lv32_105 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000101";
    constant ap_const_lv32_10C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001100";
    constant ap_const_lv32_10F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001111";
    constant ap_const_lv32_116 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010110";
    constant ap_const_lv32_119 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011001";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_123 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100011";
    constant ap_const_lv32_12A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101010";
    constant ap_const_lv32_12D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101101";
    constant ap_const_lv32_134 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110100";
    constant ap_const_lv32_137 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110111";
    constant ap_const_lv32_13E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111110";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer13_out_blk_n : STD_LOGIC;
    signal layer14_out_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln531_fu_293_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln3_fu_613_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_s_fu_297_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_15_fu_631_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_s_fu_637_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_5_fu_307_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_16_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_5_fu_661_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_6_fu_317_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_17_fu_679_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_6_fu_685_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_7_fu_327_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_18_fu_703_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_7_fu_709_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_8_fu_337_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_19_fu_727_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_8_fu_733_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_9_fu_347_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_20_fu_751_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_9_fu_757_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_1_fu_357_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_21_fu_775_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_1_fu_781_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_2_fu_367_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_22_fu_799_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_2_fu_805_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_3_fu_377_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_23_fu_823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_3_fu_829_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_4_fu_387_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_24_fu_847_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_4_fu_853_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_10_fu_397_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_25_fu_871_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_10_fu_877_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_11_fu_407_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_26_fu_895_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_11_fu_901_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_12_fu_417_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_27_fu_919_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_12_fu_925_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_13_fu_427_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_28_fu_943_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_13_fu_949_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_14_fu_437_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_29_fu_967_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_14_fu_973_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_15_fu_447_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_30_fu_991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_15_fu_997_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_16_fu_457_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_31_fu_1015_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_16_fu_1021_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_17_fu_467_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_32_fu_1039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_17_fu_1045_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_18_fu_477_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_33_fu_1063_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_18_fu_1069_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_19_fu_487_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_34_fu_1087_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_19_fu_1093_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_20_fu_497_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_35_fu_1111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_20_fu_1117_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_21_fu_507_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_36_fu_1135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_21_fu_1141_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_22_fu_517_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_37_fu_1159_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_22_fu_1165_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_23_fu_527_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_38_fu_1183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_23_fu_1189_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_24_fu_537_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_39_fu_1207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_24_fu_1213_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_25_fu_547_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_40_fu_1231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_25_fu_1237_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_26_fu_557_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_41_fu_1255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_26_fu_1261_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_27_fu_567_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_42_fu_1279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_27_fu_1285_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_28_fu_577_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_43_fu_1303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_28_fu_1309_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_29_fu_587_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_44_fu_1327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_29_fu_1333_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln531_30_fu_597_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln538_45_fu_1351_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln539_30_fu_1357_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_45_fu_1367_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_44_fu_1343_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_43_fu_1319_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_42_fu_1295_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_41_fu_1271_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_40_fu_1247_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_39_fu_1223_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_38_fu_1199_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_37_fu_1175_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_36_fu_1151_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_35_fu_1127_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_34_fu_1103_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_33_fu_1079_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_32_fu_1055_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_31_fu_1031_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_30_fu_1007_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_29_fu_983_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_28_fu_959_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_27_fu_935_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_26_fu_911_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_25_fu_887_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_24_fu_863_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_23_fu_839_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_22_fu_815_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_21_fu_791_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_20_fu_767_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_19_fu_743_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_18_fu_719_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_17_fu_695_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_16_fu_671_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_15_fu_647_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln538_fu_623_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer13_out_empty_n, layer14_out_full_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer14_out_full_n = ap_const_logic_0) or (layer13_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    icmp_ln538_15_fu_631_p2 <= "1" when (signed(trunc_ln531_s_fu_297_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_16_fu_655_p2 <= "1" when (signed(trunc_ln531_5_fu_307_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_17_fu_679_p2 <= "1" when (signed(trunc_ln531_6_fu_317_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_18_fu_703_p2 <= "1" when (signed(trunc_ln531_7_fu_327_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_19_fu_727_p2 <= "1" when (signed(trunc_ln531_8_fu_337_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_20_fu_751_p2 <= "1" when (signed(trunc_ln531_9_fu_347_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_21_fu_775_p2 <= "1" when (signed(trunc_ln531_1_fu_357_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_22_fu_799_p2 <= "1" when (signed(trunc_ln531_2_fu_367_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_23_fu_823_p2 <= "1" when (signed(trunc_ln531_3_fu_377_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_24_fu_847_p2 <= "1" when (signed(trunc_ln531_4_fu_387_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_25_fu_871_p2 <= "1" when (signed(trunc_ln531_10_fu_397_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_26_fu_895_p2 <= "1" when (signed(trunc_ln531_11_fu_407_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_27_fu_919_p2 <= "1" when (signed(trunc_ln531_12_fu_417_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_28_fu_943_p2 <= "1" when (signed(trunc_ln531_13_fu_427_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_29_fu_967_p2 <= "1" when (signed(trunc_ln531_14_fu_437_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_30_fu_991_p2 <= "1" when (signed(trunc_ln531_15_fu_447_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_31_fu_1015_p2 <= "1" when (signed(trunc_ln531_16_fu_457_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_32_fu_1039_p2 <= "1" when (signed(trunc_ln531_17_fu_467_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_33_fu_1063_p2 <= "1" when (signed(trunc_ln531_18_fu_477_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_34_fu_1087_p2 <= "1" when (signed(trunc_ln531_19_fu_487_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_35_fu_1111_p2 <= "1" when (signed(trunc_ln531_20_fu_497_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_36_fu_1135_p2 <= "1" when (signed(trunc_ln531_21_fu_507_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_37_fu_1159_p2 <= "1" when (signed(trunc_ln531_22_fu_517_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_38_fu_1183_p2 <= "1" when (signed(trunc_ln531_23_fu_527_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_39_fu_1207_p2 <= "1" when (signed(trunc_ln531_24_fu_537_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_40_fu_1231_p2 <= "1" when (signed(trunc_ln531_25_fu_547_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_41_fu_1255_p2 <= "1" when (signed(trunc_ln531_26_fu_557_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_42_fu_1279_p2 <= "1" when (signed(trunc_ln531_27_fu_567_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_43_fu_1303_p2 <= "1" when (signed(trunc_ln531_28_fu_577_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_44_fu_1327_p2 <= "1" when (signed(trunc_ln531_29_fu_587_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_45_fu_1351_p2 <= "1" when (signed(trunc_ln531_30_fu_597_p4) > signed(ap_const_lv10_0)) else "0";
    icmp_ln538_fu_607_p2 <= "1" when (signed(trunc_ln531_fu_293_p1) > signed(ap_const_lv10_0)) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer13_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer13_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer13_out_blk_n <= layer13_out_empty_n;
        else 
            layer13_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer13_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer13_out_read <= ap_const_logic_1;
        else 
            layer13_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer14_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer14_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer14_out_blk_n <= layer14_out_full_n;
        else 
            layer14_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer14_out_din <= (((((((((((((((((((((((((((((((select_ln538_45_fu_1367_p3 & select_ln538_44_fu_1343_p3) & select_ln538_43_fu_1319_p3) & select_ln538_42_fu_1295_p3) & select_ln538_41_fu_1271_p3) & select_ln538_40_fu_1247_p3) & select_ln538_39_fu_1223_p3) & select_ln538_38_fu_1199_p3) & select_ln538_37_fu_1175_p3) & select_ln538_36_fu_1151_p3) & select_ln538_35_fu_1127_p3) & select_ln538_34_fu_1103_p3) & select_ln538_33_fu_1079_p3) & select_ln538_32_fu_1055_p3) & select_ln538_31_fu_1031_p3) & select_ln538_30_fu_1007_p3) & select_ln538_29_fu_983_p3) & select_ln538_28_fu_959_p3) & select_ln538_27_fu_935_p3) & select_ln538_26_fu_911_p3) & select_ln538_25_fu_887_p3) & select_ln538_24_fu_863_p3) & select_ln538_23_fu_839_p3) & select_ln538_22_fu_815_p3) & select_ln538_21_fu_791_p3) & select_ln538_20_fu_767_p3) & select_ln538_19_fu_743_p3) & select_ln538_18_fu_719_p3) & select_ln538_17_fu_695_p3) & select_ln538_16_fu_671_p3) & select_ln538_15_fu_647_p3) & select_ln538_fu_623_p3);

    layer14_out_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer14_out_write <= ap_const_logic_1;
        else 
            layer14_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln538_15_fu_647_p3 <= 
        trunc_ln539_s_fu_637_p4 when (icmp_ln538_15_fu_631_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_16_fu_671_p3 <= 
        trunc_ln539_5_fu_661_p4 when (icmp_ln538_16_fu_655_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_17_fu_695_p3 <= 
        trunc_ln539_6_fu_685_p4 when (icmp_ln538_17_fu_679_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_18_fu_719_p3 <= 
        trunc_ln539_7_fu_709_p4 when (icmp_ln538_18_fu_703_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_19_fu_743_p3 <= 
        trunc_ln539_8_fu_733_p4 when (icmp_ln538_19_fu_727_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_20_fu_767_p3 <= 
        trunc_ln539_9_fu_757_p4 when (icmp_ln538_20_fu_751_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_21_fu_791_p3 <= 
        trunc_ln539_1_fu_781_p4 when (icmp_ln538_21_fu_775_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_22_fu_815_p3 <= 
        trunc_ln539_2_fu_805_p4 when (icmp_ln538_22_fu_799_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_23_fu_839_p3 <= 
        trunc_ln539_3_fu_829_p4 when (icmp_ln538_23_fu_823_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_24_fu_863_p3 <= 
        trunc_ln539_4_fu_853_p4 when (icmp_ln538_24_fu_847_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_25_fu_887_p3 <= 
        trunc_ln539_10_fu_877_p4 when (icmp_ln538_25_fu_871_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_26_fu_911_p3 <= 
        trunc_ln539_11_fu_901_p4 when (icmp_ln538_26_fu_895_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_27_fu_935_p3 <= 
        trunc_ln539_12_fu_925_p4 when (icmp_ln538_27_fu_919_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_28_fu_959_p3 <= 
        trunc_ln539_13_fu_949_p4 when (icmp_ln538_28_fu_943_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_29_fu_983_p3 <= 
        trunc_ln539_14_fu_973_p4 when (icmp_ln538_29_fu_967_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_30_fu_1007_p3 <= 
        trunc_ln539_15_fu_997_p4 when (icmp_ln538_30_fu_991_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_31_fu_1031_p3 <= 
        trunc_ln539_16_fu_1021_p4 when (icmp_ln538_31_fu_1015_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_32_fu_1055_p3 <= 
        trunc_ln539_17_fu_1045_p4 when (icmp_ln538_32_fu_1039_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_33_fu_1079_p3 <= 
        trunc_ln539_18_fu_1069_p4 when (icmp_ln538_33_fu_1063_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_34_fu_1103_p3 <= 
        trunc_ln539_19_fu_1093_p4 when (icmp_ln538_34_fu_1087_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_35_fu_1127_p3 <= 
        trunc_ln539_20_fu_1117_p4 when (icmp_ln538_35_fu_1111_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_36_fu_1151_p3 <= 
        trunc_ln539_21_fu_1141_p4 when (icmp_ln538_36_fu_1135_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_37_fu_1175_p3 <= 
        trunc_ln539_22_fu_1165_p4 when (icmp_ln538_37_fu_1159_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_38_fu_1199_p3 <= 
        trunc_ln539_23_fu_1189_p4 when (icmp_ln538_38_fu_1183_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_39_fu_1223_p3 <= 
        trunc_ln539_24_fu_1213_p4 when (icmp_ln538_39_fu_1207_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_40_fu_1247_p3 <= 
        trunc_ln539_25_fu_1237_p4 when (icmp_ln538_40_fu_1231_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_41_fu_1271_p3 <= 
        trunc_ln539_26_fu_1261_p4 when (icmp_ln538_41_fu_1255_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_42_fu_1295_p3 <= 
        trunc_ln539_27_fu_1285_p4 when (icmp_ln538_42_fu_1279_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_43_fu_1319_p3 <= 
        trunc_ln539_28_fu_1309_p4 when (icmp_ln538_43_fu_1303_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_44_fu_1343_p3 <= 
        trunc_ln539_29_fu_1333_p4 when (icmp_ln538_44_fu_1327_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_45_fu_1367_p3 <= 
        trunc_ln539_30_fu_1357_p4 when (icmp_ln538_45_fu_1351_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln538_fu_623_p3 <= 
        trunc_ln3_fu_613_p4 when (icmp_ln538_fu_607_p2(0) = '1') else 
        ap_const_lv8_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln3_fu_613_p4 <= layer13_out_dout(8 downto 1);
    trunc_ln531_10_fu_397_p4 <= layer13_out_dout(119 downto 110);
    trunc_ln531_11_fu_407_p4 <= layer13_out_dout(129 downto 120);
    trunc_ln531_12_fu_417_p4 <= layer13_out_dout(139 downto 130);
    trunc_ln531_13_fu_427_p4 <= layer13_out_dout(149 downto 140);
    trunc_ln531_14_fu_437_p4 <= layer13_out_dout(159 downto 150);
    trunc_ln531_15_fu_447_p4 <= layer13_out_dout(169 downto 160);
    trunc_ln531_16_fu_457_p4 <= layer13_out_dout(179 downto 170);
    trunc_ln531_17_fu_467_p4 <= layer13_out_dout(189 downto 180);
    trunc_ln531_18_fu_477_p4 <= layer13_out_dout(199 downto 190);
    trunc_ln531_19_fu_487_p4 <= layer13_out_dout(209 downto 200);
    trunc_ln531_1_fu_357_p4 <= layer13_out_dout(79 downto 70);
    trunc_ln531_20_fu_497_p4 <= layer13_out_dout(219 downto 210);
    trunc_ln531_21_fu_507_p4 <= layer13_out_dout(229 downto 220);
    trunc_ln531_22_fu_517_p4 <= layer13_out_dout(239 downto 230);
    trunc_ln531_23_fu_527_p4 <= layer13_out_dout(249 downto 240);
    trunc_ln531_24_fu_537_p4 <= layer13_out_dout(259 downto 250);
    trunc_ln531_25_fu_547_p4 <= layer13_out_dout(269 downto 260);
    trunc_ln531_26_fu_557_p4 <= layer13_out_dout(279 downto 270);
    trunc_ln531_27_fu_567_p4 <= layer13_out_dout(289 downto 280);
    trunc_ln531_28_fu_577_p4 <= layer13_out_dout(299 downto 290);
    trunc_ln531_29_fu_587_p4 <= layer13_out_dout(309 downto 300);
    trunc_ln531_2_fu_367_p4 <= layer13_out_dout(89 downto 80);
    trunc_ln531_30_fu_597_p4 <= layer13_out_dout(319 downto 310);
    trunc_ln531_3_fu_377_p4 <= layer13_out_dout(99 downto 90);
    trunc_ln531_4_fu_387_p4 <= layer13_out_dout(109 downto 100);
    trunc_ln531_5_fu_307_p4 <= layer13_out_dout(29 downto 20);
    trunc_ln531_6_fu_317_p4 <= layer13_out_dout(39 downto 30);
    trunc_ln531_7_fu_327_p4 <= layer13_out_dout(49 downto 40);
    trunc_ln531_8_fu_337_p4 <= layer13_out_dout(59 downto 50);
    trunc_ln531_9_fu_347_p4 <= layer13_out_dout(69 downto 60);
    trunc_ln531_fu_293_p1 <= layer13_out_dout(10 - 1 downto 0);
    trunc_ln531_s_fu_297_p4 <= layer13_out_dout(19 downto 10);
    trunc_ln539_10_fu_877_p4 <= layer13_out_dout(118 downto 111);
    trunc_ln539_11_fu_901_p4 <= layer13_out_dout(128 downto 121);
    trunc_ln539_12_fu_925_p4 <= layer13_out_dout(138 downto 131);
    trunc_ln539_13_fu_949_p4 <= layer13_out_dout(148 downto 141);
    trunc_ln539_14_fu_973_p4 <= layer13_out_dout(158 downto 151);
    trunc_ln539_15_fu_997_p4 <= layer13_out_dout(168 downto 161);
    trunc_ln539_16_fu_1021_p4 <= layer13_out_dout(178 downto 171);
    trunc_ln539_17_fu_1045_p4 <= layer13_out_dout(188 downto 181);
    trunc_ln539_18_fu_1069_p4 <= layer13_out_dout(198 downto 191);
    trunc_ln539_19_fu_1093_p4 <= layer13_out_dout(208 downto 201);
    trunc_ln539_1_fu_781_p4 <= layer13_out_dout(78 downto 71);
    trunc_ln539_20_fu_1117_p4 <= layer13_out_dout(218 downto 211);
    trunc_ln539_21_fu_1141_p4 <= layer13_out_dout(228 downto 221);
    trunc_ln539_22_fu_1165_p4 <= layer13_out_dout(238 downto 231);
    trunc_ln539_23_fu_1189_p4 <= layer13_out_dout(248 downto 241);
    trunc_ln539_24_fu_1213_p4 <= layer13_out_dout(258 downto 251);
    trunc_ln539_25_fu_1237_p4 <= layer13_out_dout(268 downto 261);
    trunc_ln539_26_fu_1261_p4 <= layer13_out_dout(278 downto 271);
    trunc_ln539_27_fu_1285_p4 <= layer13_out_dout(288 downto 281);
    trunc_ln539_28_fu_1309_p4 <= layer13_out_dout(298 downto 291);
    trunc_ln539_29_fu_1333_p4 <= layer13_out_dout(308 downto 301);
    trunc_ln539_2_fu_805_p4 <= layer13_out_dout(88 downto 81);
    trunc_ln539_30_fu_1357_p4 <= layer13_out_dout(318 downto 311);
    trunc_ln539_3_fu_829_p4 <= layer13_out_dout(98 downto 91);
    trunc_ln539_4_fu_853_p4 <= layer13_out_dout(108 downto 101);
    trunc_ln539_5_fu_661_p4 <= layer13_out_dout(28 downto 21);
    trunc_ln539_6_fu_685_p4 <= layer13_out_dout(38 downto 31);
    trunc_ln539_7_fu_709_p4 <= layer13_out_dout(48 downto 41);
    trunc_ln539_8_fu_733_p4 <= layer13_out_dout(58 downto 51);
    trunc_ln539_9_fu_757_p4 <= layer13_out_dout(68 downto 61);
    trunc_ln539_s_fu_637_p4 <= layer13_out_dout(18 downto 11);
end behav;
