-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_thresholded_relu_array_ap_fixed_array_thresholdedrelu_config14_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer13_out_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    layer13_out_empty_n : IN STD_LOGIC;
    layer13_out_read : OUT STD_LOGIC;
    layer13_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer13_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer14_out_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    layer14_out_full_n : IN STD_LOGIC;
    layer14_out_write : OUT STD_LOGIC;
    layer14_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer14_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of myproject_thresholded_relu_array_ap_fixed_array_thresholdedrelu_config14_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_5E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011110";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_8E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001110";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_9E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011110";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_AE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101110";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111110";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_CE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001110";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_DE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011110";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_EE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101110";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_FE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111110";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_10F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001111";
    constant ap_const_lv32_10E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001110";
    constant ap_const_lv32_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_11E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011110";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_12F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101111";
    constant ap_const_lv32_12E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101110";
    constant ap_const_lv32_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_13E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111110";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_14F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001111";
    constant ap_const_lv32_14E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001110";
    constant ap_const_lv32_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_15E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011110";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_16F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101111";
    constant ap_const_lv32_16E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101110";
    constant ap_const_lv32_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_17E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111110";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_18F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001111";
    constant ap_const_lv32_18E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001110";
    constant ap_const_lv32_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010000";
    constant ap_const_lv32_19F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011111";
    constant ap_const_lv32_19E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011110";
    constant ap_const_lv32_1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100000";
    constant ap_const_lv32_1AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101111";
    constant ap_const_lv32_1AE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101110";
    constant ap_const_lv32_1B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111110";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111001111";
    constant ap_const_lv32_1CE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111001110";
    constant ap_const_lv32_1D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111010000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";
    constant ap_const_lv32_1DE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011110";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";
    constant ap_const_lv32_1EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111101111";
    constant ap_const_lv32_1EE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111101110";
    constant ap_const_lv32_1F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv32_1FE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111110";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer13_out_blk_n : STD_LOGIC;
    signal layer14_out_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln531_fu_227_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_fu_855_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_76_fu_231_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_fu_861_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_15_fu_235_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_15_fu_873_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_s_fu_245_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_15_fu_879_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_16_fu_255_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_16_fu_891_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_46_fu_265_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_16_fu_897_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_17_fu_275_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_17_fu_909_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_47_fu_285_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_17_fu_915_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_18_fu_295_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_18_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_48_fu_305_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_18_fu_933_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_19_fu_315_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_19_fu_945_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_49_fu_325_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_19_fu_951_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_20_fu_335_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_20_fu_963_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_50_fu_345_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_20_fu_969_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_21_fu_355_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_21_fu_981_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_51_fu_365_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_21_fu_987_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_22_fu_375_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_22_fu_999_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_52_fu_385_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_22_fu_1005_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_23_fu_395_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_23_fu_1017_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_53_fu_405_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_23_fu_1023_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_24_fu_415_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_24_fu_1035_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_54_fu_425_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_24_fu_1041_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_25_fu_435_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_25_fu_1053_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_55_fu_445_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_25_fu_1059_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_26_fu_455_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_26_fu_1071_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_56_fu_465_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_26_fu_1077_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_27_fu_475_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_27_fu_1089_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_57_fu_485_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_27_fu_1095_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_28_fu_495_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_28_fu_1107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_58_fu_505_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_28_fu_1113_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_29_fu_515_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_29_fu_1125_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_59_fu_525_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_29_fu_1131_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_30_fu_535_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_30_fu_1143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_60_fu_545_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_30_fu_1149_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_31_fu_555_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_31_fu_1161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_61_fu_565_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_31_fu_1167_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_32_fu_575_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_32_fu_1179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_62_fu_585_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_32_fu_1185_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_33_fu_595_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_33_fu_1197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_63_fu_605_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_33_fu_1203_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_34_fu_615_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_34_fu_1215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_64_fu_625_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_34_fu_1221_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_35_fu_635_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_35_fu_1233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_65_fu_645_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_35_fu_1239_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_36_fu_655_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_36_fu_1251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_66_fu_665_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_36_fu_1257_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_37_fu_675_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_37_fu_1269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_67_fu_685_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_37_fu_1275_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_38_fu_695_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_38_fu_1287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_68_fu_705_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_38_fu_1293_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_39_fu_715_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_39_fu_1305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_69_fu_725_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_39_fu_1311_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_40_fu_735_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_40_fu_1323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_70_fu_745_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_40_fu_1329_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_41_fu_755_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_41_fu_1341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_71_fu_765_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_41_fu_1347_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_42_fu_775_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_42_fu_1359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_72_fu_785_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_42_fu_1365_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_43_fu_795_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_43_fu_1377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_73_fu_805_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_43_fu_1383_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_44_fu_815_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_44_fu_1395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln531_74_fu_825_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_44_fu_1401_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln531_45_fu_835_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln538_45_fu_1413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln3_fu_845_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln538_45_fu_1419_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln538_42_fu_1409_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_41_fu_1391_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_40_fu_1373_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_39_fu_1355_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_38_fu_1337_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_37_fu_1319_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_36_fu_1301_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_35_fu_1283_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_34_fu_1265_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_33_fu_1247_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_32_fu_1229_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_31_fu_1211_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_30_fu_1193_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_29_fu_1175_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_28_fu_1157_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_27_fu_1139_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_26_fu_1121_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_25_fu_1103_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_24_fu_1085_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_23_fu_1067_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_22_fu_1049_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_21_fu_1031_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_20_fu_1013_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_19_fu_995_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_18_fu_977_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_17_fu_959_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_16_fu_941_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_15_fu_923_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_14_fu_905_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_13_fu_887_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln538_fu_869_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln544_s_fu_1427_p33 : STD_LOGIC_VECTOR (510 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer13_out_empty_n, layer14_out_full_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer14_out_full_n = ap_const_logic_0) or (layer13_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    icmp_ln538_15_fu_873_p2 <= "1" when (signed(trunc_ln531_15_fu_235_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_16_fu_891_p2 <= "1" when (signed(trunc_ln531_16_fu_255_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_17_fu_909_p2 <= "1" when (signed(trunc_ln531_17_fu_275_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_18_fu_927_p2 <= "1" when (signed(trunc_ln531_18_fu_295_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_19_fu_945_p2 <= "1" when (signed(trunc_ln531_19_fu_315_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_20_fu_963_p2 <= "1" when (signed(trunc_ln531_20_fu_335_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_21_fu_981_p2 <= "1" when (signed(trunc_ln531_21_fu_355_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_22_fu_999_p2 <= "1" when (signed(trunc_ln531_22_fu_375_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_23_fu_1017_p2 <= "1" when (signed(trunc_ln531_23_fu_395_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_24_fu_1035_p2 <= "1" when (signed(trunc_ln531_24_fu_415_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_25_fu_1053_p2 <= "1" when (signed(trunc_ln531_25_fu_435_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_26_fu_1071_p2 <= "1" when (signed(trunc_ln531_26_fu_455_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_27_fu_1089_p2 <= "1" when (signed(trunc_ln531_27_fu_475_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_28_fu_1107_p2 <= "1" when (signed(trunc_ln531_28_fu_495_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_29_fu_1125_p2 <= "1" when (signed(trunc_ln531_29_fu_515_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_30_fu_1143_p2 <= "1" when (signed(trunc_ln531_30_fu_535_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_31_fu_1161_p2 <= "1" when (signed(trunc_ln531_31_fu_555_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_32_fu_1179_p2 <= "1" when (signed(trunc_ln531_32_fu_575_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_33_fu_1197_p2 <= "1" when (signed(trunc_ln531_33_fu_595_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_34_fu_1215_p2 <= "1" when (signed(trunc_ln531_34_fu_615_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_35_fu_1233_p2 <= "1" when (signed(trunc_ln531_35_fu_635_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_36_fu_1251_p2 <= "1" when (signed(trunc_ln531_36_fu_655_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_37_fu_1269_p2 <= "1" when (signed(trunc_ln531_37_fu_675_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_38_fu_1287_p2 <= "1" when (signed(trunc_ln531_38_fu_695_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_39_fu_1305_p2 <= "1" when (signed(trunc_ln531_39_fu_715_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_40_fu_1323_p2 <= "1" when (signed(trunc_ln531_40_fu_735_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_41_fu_1341_p2 <= "1" when (signed(trunc_ln531_41_fu_755_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_42_fu_1359_p2 <= "1" when (signed(trunc_ln531_42_fu_775_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_43_fu_1377_p2 <= "1" when (signed(trunc_ln531_43_fu_795_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_44_fu_1395_p2 <= "1" when (signed(trunc_ln531_44_fu_815_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_45_fu_1413_p2 <= "1" when (signed(trunc_ln531_45_fu_835_p4) > signed(ap_const_lv16_0)) else "0";
    icmp_ln538_fu_855_p2 <= "1" when (signed(trunc_ln531_fu_227_p1) > signed(ap_const_lv16_0)) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer13_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer13_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer13_out_blk_n <= layer13_out_empty_n;
        else 
            layer13_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer13_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer13_out_read <= ap_const_logic_1;
        else 
            layer13_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer14_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer14_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer14_out_blk_n <= layer14_out_full_n;
        else 
            layer14_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer14_out_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln544_s_fu_1427_p33),512));

    layer14_out_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer14_out_write <= ap_const_logic_1;
        else 
            layer14_out_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln544_s_fu_1427_p33 <= (((((((((((((((((((((((((((((((select_ln538_45_fu_1419_p3 & zext_ln538_42_fu_1409_p1) & zext_ln538_41_fu_1391_p1) & zext_ln538_40_fu_1373_p1) & zext_ln538_39_fu_1355_p1) & zext_ln538_38_fu_1337_p1) & zext_ln538_37_fu_1319_p1) & zext_ln538_36_fu_1301_p1) & zext_ln538_35_fu_1283_p1) & zext_ln538_34_fu_1265_p1) & zext_ln538_33_fu_1247_p1) & zext_ln538_32_fu_1229_p1) & zext_ln538_31_fu_1211_p1) & zext_ln538_30_fu_1193_p1) & zext_ln538_29_fu_1175_p1) & zext_ln538_28_fu_1157_p1) & zext_ln538_27_fu_1139_p1) & zext_ln538_26_fu_1121_p1) & zext_ln538_25_fu_1103_p1) & zext_ln538_24_fu_1085_p1) & zext_ln538_23_fu_1067_p1) & zext_ln538_22_fu_1049_p1) & zext_ln538_21_fu_1031_p1) & zext_ln538_20_fu_1013_p1) & zext_ln538_19_fu_995_p1) & zext_ln538_18_fu_977_p1) & zext_ln538_17_fu_959_p1) & zext_ln538_16_fu_941_p1) & zext_ln538_15_fu_923_p1) & zext_ln538_14_fu_905_p1) & zext_ln538_13_fu_887_p1) & zext_ln538_fu_869_p1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln538_15_fu_879_p3 <= 
        trunc_ln531_s_fu_245_p4 when (icmp_ln538_15_fu_873_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_16_fu_897_p3 <= 
        trunc_ln531_46_fu_265_p4 when (icmp_ln538_16_fu_891_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_17_fu_915_p3 <= 
        trunc_ln531_47_fu_285_p4 when (icmp_ln538_17_fu_909_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_18_fu_933_p3 <= 
        trunc_ln531_48_fu_305_p4 when (icmp_ln538_18_fu_927_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_19_fu_951_p3 <= 
        trunc_ln531_49_fu_325_p4 when (icmp_ln538_19_fu_945_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_20_fu_969_p3 <= 
        trunc_ln531_50_fu_345_p4 when (icmp_ln538_20_fu_963_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_21_fu_987_p3 <= 
        trunc_ln531_51_fu_365_p4 when (icmp_ln538_21_fu_981_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_22_fu_1005_p3 <= 
        trunc_ln531_52_fu_385_p4 when (icmp_ln538_22_fu_999_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_23_fu_1023_p3 <= 
        trunc_ln531_53_fu_405_p4 when (icmp_ln538_23_fu_1017_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_24_fu_1041_p3 <= 
        trunc_ln531_54_fu_425_p4 when (icmp_ln538_24_fu_1035_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_25_fu_1059_p3 <= 
        trunc_ln531_55_fu_445_p4 when (icmp_ln538_25_fu_1053_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_26_fu_1077_p3 <= 
        trunc_ln531_56_fu_465_p4 when (icmp_ln538_26_fu_1071_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_27_fu_1095_p3 <= 
        trunc_ln531_57_fu_485_p4 when (icmp_ln538_27_fu_1089_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_28_fu_1113_p3 <= 
        trunc_ln531_58_fu_505_p4 when (icmp_ln538_28_fu_1107_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_29_fu_1131_p3 <= 
        trunc_ln531_59_fu_525_p4 when (icmp_ln538_29_fu_1125_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_30_fu_1149_p3 <= 
        trunc_ln531_60_fu_545_p4 when (icmp_ln538_30_fu_1143_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_31_fu_1167_p3 <= 
        trunc_ln531_61_fu_565_p4 when (icmp_ln538_31_fu_1161_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_32_fu_1185_p3 <= 
        trunc_ln531_62_fu_585_p4 when (icmp_ln538_32_fu_1179_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_33_fu_1203_p3 <= 
        trunc_ln531_63_fu_605_p4 when (icmp_ln538_33_fu_1197_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_34_fu_1221_p3 <= 
        trunc_ln531_64_fu_625_p4 when (icmp_ln538_34_fu_1215_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_35_fu_1239_p3 <= 
        trunc_ln531_65_fu_645_p4 when (icmp_ln538_35_fu_1233_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_36_fu_1257_p3 <= 
        trunc_ln531_66_fu_665_p4 when (icmp_ln538_36_fu_1251_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_37_fu_1275_p3 <= 
        trunc_ln531_67_fu_685_p4 when (icmp_ln538_37_fu_1269_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_38_fu_1293_p3 <= 
        trunc_ln531_68_fu_705_p4 when (icmp_ln538_38_fu_1287_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_39_fu_1311_p3 <= 
        trunc_ln531_69_fu_725_p4 when (icmp_ln538_39_fu_1305_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_40_fu_1329_p3 <= 
        trunc_ln531_70_fu_745_p4 when (icmp_ln538_40_fu_1323_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_41_fu_1347_p3 <= 
        trunc_ln531_71_fu_765_p4 when (icmp_ln538_41_fu_1341_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_42_fu_1365_p3 <= 
        trunc_ln531_72_fu_785_p4 when (icmp_ln538_42_fu_1359_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_43_fu_1383_p3 <= 
        trunc_ln531_73_fu_805_p4 when (icmp_ln538_43_fu_1377_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_44_fu_1401_p3 <= 
        trunc_ln531_74_fu_825_p4 when (icmp_ln538_44_fu_1395_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_45_fu_1419_p3 <= 
        trunc_ln3_fu_845_p4 when (icmp_ln538_45_fu_1413_p2(0) = '1') else 
        ap_const_lv15_0;
    select_ln538_fu_861_p3 <= 
        trunc_ln531_76_fu_231_p1 when (icmp_ln538_fu_855_p2(0) = '1') else 
        ap_const_lv15_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln3_fu_845_p4 <= layer13_out_dout(510 downto 496);
    trunc_ln531_15_fu_235_p4 <= layer13_out_dout(31 downto 16);
    trunc_ln531_16_fu_255_p4 <= layer13_out_dout(47 downto 32);
    trunc_ln531_17_fu_275_p4 <= layer13_out_dout(63 downto 48);
    trunc_ln531_18_fu_295_p4 <= layer13_out_dout(79 downto 64);
    trunc_ln531_19_fu_315_p4 <= layer13_out_dout(95 downto 80);
    trunc_ln531_20_fu_335_p4 <= layer13_out_dout(111 downto 96);
    trunc_ln531_21_fu_355_p4 <= layer13_out_dout(127 downto 112);
    trunc_ln531_22_fu_375_p4 <= layer13_out_dout(143 downto 128);
    trunc_ln531_23_fu_395_p4 <= layer13_out_dout(159 downto 144);
    trunc_ln531_24_fu_415_p4 <= layer13_out_dout(175 downto 160);
    trunc_ln531_25_fu_435_p4 <= layer13_out_dout(191 downto 176);
    trunc_ln531_26_fu_455_p4 <= layer13_out_dout(207 downto 192);
    trunc_ln531_27_fu_475_p4 <= layer13_out_dout(223 downto 208);
    trunc_ln531_28_fu_495_p4 <= layer13_out_dout(239 downto 224);
    trunc_ln531_29_fu_515_p4 <= layer13_out_dout(255 downto 240);
    trunc_ln531_30_fu_535_p4 <= layer13_out_dout(271 downto 256);
    trunc_ln531_31_fu_555_p4 <= layer13_out_dout(287 downto 272);
    trunc_ln531_32_fu_575_p4 <= layer13_out_dout(303 downto 288);
    trunc_ln531_33_fu_595_p4 <= layer13_out_dout(319 downto 304);
    trunc_ln531_34_fu_615_p4 <= layer13_out_dout(335 downto 320);
    trunc_ln531_35_fu_635_p4 <= layer13_out_dout(351 downto 336);
    trunc_ln531_36_fu_655_p4 <= layer13_out_dout(367 downto 352);
    trunc_ln531_37_fu_675_p4 <= layer13_out_dout(383 downto 368);
    trunc_ln531_38_fu_695_p4 <= layer13_out_dout(399 downto 384);
    trunc_ln531_39_fu_715_p4 <= layer13_out_dout(415 downto 400);
    trunc_ln531_40_fu_735_p4 <= layer13_out_dout(431 downto 416);
    trunc_ln531_41_fu_755_p4 <= layer13_out_dout(447 downto 432);
    trunc_ln531_42_fu_775_p4 <= layer13_out_dout(463 downto 448);
    trunc_ln531_43_fu_795_p4 <= layer13_out_dout(479 downto 464);
    trunc_ln531_44_fu_815_p4 <= layer13_out_dout(495 downto 480);
    trunc_ln531_45_fu_835_p4 <= layer13_out_dout(511 downto 496);
    trunc_ln531_46_fu_265_p4 <= layer13_out_dout(46 downto 32);
    trunc_ln531_47_fu_285_p4 <= layer13_out_dout(62 downto 48);
    trunc_ln531_48_fu_305_p4 <= layer13_out_dout(78 downto 64);
    trunc_ln531_49_fu_325_p4 <= layer13_out_dout(94 downto 80);
    trunc_ln531_50_fu_345_p4 <= layer13_out_dout(110 downto 96);
    trunc_ln531_51_fu_365_p4 <= layer13_out_dout(126 downto 112);
    trunc_ln531_52_fu_385_p4 <= layer13_out_dout(142 downto 128);
    trunc_ln531_53_fu_405_p4 <= layer13_out_dout(158 downto 144);
    trunc_ln531_54_fu_425_p4 <= layer13_out_dout(174 downto 160);
    trunc_ln531_55_fu_445_p4 <= layer13_out_dout(190 downto 176);
    trunc_ln531_56_fu_465_p4 <= layer13_out_dout(206 downto 192);
    trunc_ln531_57_fu_485_p4 <= layer13_out_dout(222 downto 208);
    trunc_ln531_58_fu_505_p4 <= layer13_out_dout(238 downto 224);
    trunc_ln531_59_fu_525_p4 <= layer13_out_dout(254 downto 240);
    trunc_ln531_60_fu_545_p4 <= layer13_out_dout(270 downto 256);
    trunc_ln531_61_fu_565_p4 <= layer13_out_dout(286 downto 272);
    trunc_ln531_62_fu_585_p4 <= layer13_out_dout(302 downto 288);
    trunc_ln531_63_fu_605_p4 <= layer13_out_dout(318 downto 304);
    trunc_ln531_64_fu_625_p4 <= layer13_out_dout(334 downto 320);
    trunc_ln531_65_fu_645_p4 <= layer13_out_dout(350 downto 336);
    trunc_ln531_66_fu_665_p4 <= layer13_out_dout(366 downto 352);
    trunc_ln531_67_fu_685_p4 <= layer13_out_dout(382 downto 368);
    trunc_ln531_68_fu_705_p4 <= layer13_out_dout(398 downto 384);
    trunc_ln531_69_fu_725_p4 <= layer13_out_dout(414 downto 400);
    trunc_ln531_70_fu_745_p4 <= layer13_out_dout(430 downto 416);
    trunc_ln531_71_fu_765_p4 <= layer13_out_dout(446 downto 432);
    trunc_ln531_72_fu_785_p4 <= layer13_out_dout(462 downto 448);
    trunc_ln531_73_fu_805_p4 <= layer13_out_dout(478 downto 464);
    trunc_ln531_74_fu_825_p4 <= layer13_out_dout(494 downto 480);
    trunc_ln531_76_fu_231_p1 <= layer13_out_dout(15 - 1 downto 0);
    trunc_ln531_fu_227_p1 <= layer13_out_dout(16 - 1 downto 0);
    trunc_ln531_s_fu_245_p4 <= layer13_out_dout(30 downto 16);
    zext_ln538_13_fu_887_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_15_fu_879_p3),16));
    zext_ln538_14_fu_905_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_16_fu_897_p3),16));
    zext_ln538_15_fu_923_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_17_fu_915_p3),16));
    zext_ln538_16_fu_941_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_18_fu_933_p3),16));
    zext_ln538_17_fu_959_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_19_fu_951_p3),16));
    zext_ln538_18_fu_977_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_20_fu_969_p3),16));
    zext_ln538_19_fu_995_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_21_fu_987_p3),16));
    zext_ln538_20_fu_1013_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_22_fu_1005_p3),16));
    zext_ln538_21_fu_1031_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_23_fu_1023_p3),16));
    zext_ln538_22_fu_1049_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_24_fu_1041_p3),16));
    zext_ln538_23_fu_1067_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_25_fu_1059_p3),16));
    zext_ln538_24_fu_1085_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_26_fu_1077_p3),16));
    zext_ln538_25_fu_1103_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_27_fu_1095_p3),16));
    zext_ln538_26_fu_1121_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_28_fu_1113_p3),16));
    zext_ln538_27_fu_1139_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_29_fu_1131_p3),16));
    zext_ln538_28_fu_1157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_30_fu_1149_p3),16));
    zext_ln538_29_fu_1175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_31_fu_1167_p3),16));
    zext_ln538_30_fu_1193_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_32_fu_1185_p3),16));
    zext_ln538_31_fu_1211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_33_fu_1203_p3),16));
    zext_ln538_32_fu_1229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_34_fu_1221_p3),16));
    zext_ln538_33_fu_1247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_35_fu_1239_p3),16));
    zext_ln538_34_fu_1265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_36_fu_1257_p3),16));
    zext_ln538_35_fu_1283_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_37_fu_1275_p3),16));
    zext_ln538_36_fu_1301_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_38_fu_1293_p3),16));
    zext_ln538_37_fu_1319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_39_fu_1311_p3),16));
    zext_ln538_38_fu_1337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_40_fu_1329_p3),16));
    zext_ln538_39_fu_1355_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_41_fu_1347_p3),16));
    zext_ln538_40_fu_1373_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_42_fu_1365_p3),16));
    zext_ln538_41_fu_1391_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_43_fu_1383_p3),16));
    zext_ln538_42_fu_1409_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_44_fu_1401_p3),16));
    zext_ln538_fu_869_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln538_fu_861_p3),16));
end behav;
