// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_40,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_41,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_42,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_43,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_44,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_45,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_40;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_41;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_42;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_43;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_44;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_45;
output  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld;
output  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_ap_vld;
output  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_ap_vld;
output  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_ap_vld;
output  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_ap_vld;
output  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_ap_vld;
input  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_i;
output  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_o_ap_vld;
input  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_i;
output  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_o_ap_vld;
input  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_i;
output  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_o_ap_vld;
input  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_i;
output  [15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_o_ap_vld;
input  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_i;
output  [15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_o_ap_vld;

reg ap_idle;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_ap_vld;
reg[15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_o_ap_vld;
reg[15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_o_ap_vld;
reg[15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_o_ap_vld;
reg[15:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_o_ap_vld;
reg[15:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln161_fu_144_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [15:0] tmp_fu_172_p11;
wire   [1:0] trunc_ln161_fu_156_p1;
wire   [15:0] tmp_s_fu_208_p11;
wire   [15:0] tmp_1_fu_244_p11;
wire   [15:0] tmp_2_fu_280_p11;
wire   [15:0] tmp_3_fu_316_p11;
wire   [15:0] tmp_4_fu_352_p11;
reg   [2:0] i_iw_fu_96;
wire   [2:0] indvars_iv_next_fu_150_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_iw_6;
wire   [15:0] tmp_fu_172_p9;
wire   [15:0] tmp_s_fu_208_p9;
wire   [15:0] tmp_1_fu_244_p9;
wire   [15:0] tmp_2_fu_280_p9;
wire   [15:0] tmp_3_fu_316_p9;
wire   [15:0] tmp_4_fu_352_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_fu_172_p1;
wire   [1:0] tmp_fu_172_p3;
wire  signed [1:0] tmp_fu_172_p5;
wire  signed [1:0] tmp_fu_172_p7;
wire   [1:0] tmp_s_fu_208_p1;
wire   [1:0] tmp_s_fu_208_p3;
wire  signed [1:0] tmp_s_fu_208_p5;
wire  signed [1:0] tmp_s_fu_208_p7;
wire   [1:0] tmp_1_fu_244_p1;
wire   [1:0] tmp_1_fu_244_p3;
wire  signed [1:0] tmp_1_fu_244_p5;
wire  signed [1:0] tmp_1_fu_244_p7;
wire   [1:0] tmp_2_fu_280_p1;
wire   [1:0] tmp_2_fu_280_p3;
wire  signed [1:0] tmp_2_fu_280_p5;
wire  signed [1:0] tmp_2_fu_280_p7;
wire   [1:0] tmp_3_fu_316_p1;
wire   [1:0] tmp_3_fu_316_p3;
wire  signed [1:0] tmp_3_fu_316_p5;
wire  signed [1:0] tmp_3_fu_316_p7;
wire   [1:0] tmp_4_fu_352_p1;
wire   [1:0] tmp_4_fu_352_p3;
wire  signed [1:0] tmp_4_fu_352_p5;
wire  signed [1:0] tmp_4_fu_352_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_iw_fu_96 = 3'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U1(
    .din0(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_i),
    .din1(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_i),
    .din2(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_i),
    .din3(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_40),
    .def(tmp_fu_172_p9),
    .sel(trunc_ln161_fu_156_p1),
    .dout(tmp_fu_172_p11)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U2(
    .din0(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_i),
    .din1(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_i),
    .din2(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_i),
    .din3(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_41),
    .def(tmp_s_fu_208_p9),
    .sel(trunc_ln161_fu_156_p1),
    .dout(tmp_s_fu_208_p11)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U3(
    .din0(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_i),
    .din1(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_i),
    .din2(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_i),
    .din3(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_42),
    .def(tmp_1_fu_244_p9),
    .sel(trunc_ln161_fu_156_p1),
    .dout(tmp_1_fu_244_p11)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U4(
    .din0(void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_i),
    .din1(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_i),
    .din2(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_i),
    .din3(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_43),
    .def(tmp_2_fu_280_p9),
    .sel(trunc_ln161_fu_156_p1),
    .dout(tmp_2_fu_280_p11)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U5(
    .din0(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_i),
    .din1(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_i),
    .din2(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_i),
    .din3(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_44),
    .def(tmp_3_fu_316_p9),
    .sel(trunc_ln161_fu_156_p1),
    .dout(tmp_3_fu_316_p11)
);

(* dissolve_hierarchy = "yes" *) myproject_sparsemux_9_2_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
sparsemux_9_2_16_1_1_U6(
    .din0(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_i),
    .din1(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_i),
    .din2(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_i),
    .din3(p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_45),
    .def(tmp_4_fu_352_p9),
    .sel(trunc_ln161_fu_156_p1),
    .dout(tmp_4_fu_352_p11)
);

myproject_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln161_fu_144_p2 == 1'd0)) begin
            i_iw_fu_96 <= indvars_iv_next_fu_150_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_iw_fu_96 <= 3'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_iw_6 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_iw_6 = i_iw_fu_96;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_o = tmp_s_fu_208_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_10_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_o = tmp_fu_172_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_11_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_o = tmp_4_fu_352_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_12_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_o = tmp_3_fu_316_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_13_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_o = tmp_2_fu_280_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_14_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_o = tmp_1_fu_244_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_15_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_o = tmp_s_fu_208_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_16_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_o = tmp_fu_172_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd2))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_17_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_o = tmp_4_fu_352_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_18_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_o = tmp_3_fu_316_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_19_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_o = tmp_4_fu_352_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_o = tmp_3_fu_316_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_o = tmp_2_fu_280_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_8_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_o = tmp_1_fu_244_p11;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd3))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI6ap_intILi16EELj6EEENS1_I8ap_fixed_9_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_o = tmp_1_fu_244_p11;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_o = tmp_s_fu_208_p11;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_o = tmp_fu_172_p11;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd0))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd0))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd0))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd0))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd0))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd0))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o = tmp_2_fu_280_p11;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_i;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_144_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln161_fu_156_p1 == 2'd1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln161_fu_144_p2 = ((ap_sig_allocacmp_i_iw_6 == 3'd4) ? 1'b1 : 1'b0);

assign indvars_iv_next_fu_150_p2 = (ap_sig_allocacmp_i_iw_6 + 3'd1);

assign tmp_1_fu_244_p9 = 'bx;

assign tmp_2_fu_280_p9 = 'bx;

assign tmp_3_fu_316_p9 = 'bx;

assign tmp_4_fu_352_p9 = 'bx;

assign tmp_fu_172_p9 = 'bx;

assign tmp_s_fu_208_p9 = 'bx;

assign trunc_ln161_fu_156_p1 = ap_sig_allocacmp_i_iw_6[1:0];

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_4 = tmp_4_fu_352_p11;

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_5 = tmp_3_fu_316_p11;

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_6 = tmp_2_fu_280_p11;

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_7 = tmp_1_fu_244_p11;

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_8 = tmp_s_fu_208_p11;

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_9 = tmp_fu_172_p11;

endmodule //myproject_compute_output_buffer_1d_array_array_config2_Pipeline_KernelShiftWidth
