// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_compute_output_buffer_1d_array_array_config6_Pipeline_KernelShiftWidth (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_28,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_29,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_30,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_31,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_32,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_33,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_34,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_35,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_i,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o,
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_i,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_o,
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_28;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_29;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_30;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_31;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_32;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_33;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_34;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_35;
output  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld;
output  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld;
output  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld;
output  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld;
output  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld;
output  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld;
output  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_ap_vld;
output  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_ap_vld;
input  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i;
output  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld;
input  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_i;
output  [7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o;
output   void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_i;
output  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_o_ap_vld;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_i;
output  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_o_ap_vld;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_i;
output  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_o_ap_vld;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_i;
output  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_o_ap_vld;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_i;
output  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_o_ap_vld;
input  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_i;
output  [7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_o;
output   p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_o_ap_vld;

reg ap_idle;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_ap_vld;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_ap_vld;
reg[7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld;
reg[7:0] void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o;
reg void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld;
reg[7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_o_ap_vld;
reg[7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_o_ap_vld;
reg[7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_o_ap_vld;
reg[7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_o_ap_vld;
reg[7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_o_ap_vld;
reg[7:0] p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_o;
reg p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln161_fu_132_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] select_ln167_fu_154_p3;
wire   [0:0] icmp_ln167_fu_246_p2;
wire   [7:0] select_ln167_1_fu_166_p3;
wire   [7:0] select_ln167_2_fu_178_p3;
wire   [7:0] select_ln167_3_fu_190_p3;
wire   [7:0] select_ln167_4_fu_202_p3;
wire   [7:0] select_ln167_5_fu_214_p3;
wire   [7:0] select_ln167_6_fu_226_p3;
wire   [7:0] select_ln167_7_fu_238_p3;
reg   [1:0] i_iw_fu_72;
wire   [1:0] add_ln161_fu_138_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_i_iw_5;
wire   [0:0] icmp_ln167_1_fu_148_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_iw_fu_72 = 2'd0;
#0 ap_done_reg = 1'b0;
end

myproject_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln161_fu_132_p2 == 1'd0)) begin
            i_iw_fu_72 <= add_ln161_fu_138_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_iw_fu_72 <= 2'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln161_fu_132_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_iw_5 = 2'd0;
    end else begin
        ap_sig_allocacmp_i_iw_5 = i_iw_fu_72;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_o = select_ln167_5_fu_214_p3;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_i;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_o = select_ln167_4_fu_202_p3;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_i;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_o = select_ln167_3_fu_190_p3;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_i;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_o = select_ln167_2_fu_178_p3;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_i;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_o = select_ln167_7_fu_238_p3;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_i;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_o = select_ln167_6_fu_226_p3;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_o = p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_i;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_o_ap_vld = 1'b1;
    end else begin
        p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o = select_ln167_1_fu_166_p3;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_i;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o = select_ln167_fu_154_p3;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o = void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd0) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd1) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd1) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd1) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd1) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd1) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd1) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd1) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln167_fu_246_p2 == 1'd1) & (icmp_ln161_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld = 1'b1;
    end else begin
        void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln161_fu_138_p2 = (ap_sig_allocacmp_i_iw_5 + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln161_fu_132_p2 = ((ap_sig_allocacmp_i_iw_5 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln167_1_fu_148_p2 = ((ap_sig_allocacmp_i_iw_5 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_246_p2 = ((ap_sig_allocacmp_i_iw_5 == 2'd0) ? 1'b1 : 1'b0);

assign select_ln167_1_fu_166_p3 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_29 : void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_i);

assign select_ln167_2_fu_178_p3 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_30 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_i);

assign select_ln167_3_fu_190_p3 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_31 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_i);

assign select_ln167_4_fu_202_p3 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_32 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_i);

assign select_ln167_5_fu_214_p3 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_33 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_i);

assign select_ln167_6_fu_226_p3 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_34 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_i);

assign select_ln167_7_fu_238_p3 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_35 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_i);

assign select_ln167_fu_154_p3 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_28 : void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i);

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_12 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_35 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_8_i);

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_13 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_34 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_9_i);

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_14 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_33 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_10_i);

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_15 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_32 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_11_i);

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_16 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_31 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_12_i);

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_17 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_30 : p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_13_i);

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_18 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_29 : void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_10_i);

assign void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_19 = ((icmp_ln167_1_fu_148_p2[0:0] == 1'b1) ? p_ZZN4nnet24compute_output_buffer_1dINS_5arrayI8ap_fixedILi8ELi4EL9ap_q_mode5EL9a_28 : void_compute_output_buffer_1d_array_const_stream_weight_t_bias_t_kernel_data_11_i);

endmodule //myproject_compute_output_buffer_1d_array_array_config6_Pipeline_KernelShiftWidth
